---
site_name: libkafka-asio
theme: readthedocs
pages:
    - ['index.html', 'Reference']
    - ['build_configuration.md', 'Core', 'Build Configuration']
    - ['primitives.md', 'Core', 'Primitive Types']
    - ['client.md', 'Core', 'Client']
    - ['client_configuration.md', 'Core', 'ClientConfiguration']
    - ['message.md', 'Core', 'Message']
    - ['metadata_request.md', 'Metadata API', 'MetadataRequest']
    - ['metadata_response.md', 'Metadata API', 'MetadataResponse']
    - ['produce_request.md', 'Produce API', 'ProduceRequest']
    - ['produce_response.md', 'Produce API', 'ProduceResponse']
    - ['fetch_request.md', 'Fetch API', 'FetchRequest']
    - ['fetch_response.md', 'Fetch API', 'FetchResponse']
    - ['offset_request.md', 'Offset API', 'OffsetRequest']
    - ['offset_response.md', 'Offset API', 'OffsetResponse']
    - ['consumer_metadata_request.md', 'Offset Commit/Fetch API', 'ConsumerMetadataRequest']
    - ['consumer_metadata_response.md', 'Offset Commit/Fetch API', 'ConsumerMetadataResponse']
    - ['offset_commit_request.md', 'Offset Commit/Fetch API', 'OffsetCommitRequest']
    - ['offset_commit_response.md', 'Offset Commit/Fetch API', 'OffsetCommitResponse']
    - ['offset_fetch_request.md', 'Offset Commit/Fetch API', 'OffsetFetchRequest']
    - ['offset_fetch_response.md', 'Offset Commit/Fetch API', 'OffsetFetchResponse']
